server:
  port: 8080
  error:
    include-stacktrace: never

# --- API EXTERNA Gutendex ---
gutendex:
  api:
    baseurl: https://gutendex.com

spring:
  application:
    name: literatura-api

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/literatura_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# --- Flyway ---
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    validate-on-migrate: true

# --- LOGGING ----
logging:
  level:
    root: INFO
    com.LiteraturaAPI: DEBUG