# ─────────────────────────────────────────────────────────────
# ARCHIVO DE EJEMPLO — copia esto como application.yml
# y reemplaza los valores con tus credenciales reales
# ─────────────────────────────────────────────────────────────

# --- API EXTERNA Gutendex ---
gutendex:
  api:
    baseurl: https://gutendex.com

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/NOMBRE_DATA_BASE_POSTGRESQL
    username: TU_USUARIO_POSTGRESQL  # Ejemplo: Postgresql
    password: Tu_PASSWORD_POSTGRESQL  # Ejemplo: admin123
    driver-class-name: org.postgresql.Driver